import { Component, OnInit } from '@angular/core';
import { MenuController } from '@ionic/angular';
import { Router, NavigationExtras } from  "@angular/router";

@Component({
  selector: 'app-area',
  templateUrl: './area.page.html',
  styleUrls: ['./area.page.scss'],
})
export class AreaPage implements OnInit {
  data: string;
 
  constructor(private menu: MenuController, public  router:  Router) { }

  ngOnInit() {
   // this.data = localStorage.getItem("userlevel");
   // if(this.data == 'visitor'){
      this.menu.enable(true, 'visitor');
   // }
    //if(this.data == 'member'){
     // this.menu.enable(true, 'member');
    //}
  } 

  gotoDetail(param : string){
    let imgName = "";
    let description = "";
    let director = "";
    let email = "";
    let website = "";
    let title = "";
    switch(param){
      case 'eastern':
        title = "Eastern Area";
        imgName = 'eastern-area.png';
        description = 'The legacy of The Philadelphia Links is the story of The Links, Incorporated. It is also the story of the Eastern Area. What began as the Philadelphia Club in 1946, along with 13 other clubs created in its own image, was reborn as National Links in 1949.  In 1954, when the Links decentralized into four geographical Areas, the Philadelphia Chapter became the anchor for the Eastern Area. The Eastern Area is comprised of 76 chapters in the states of Connecticut, Delaware, Maryland, Massachusetts, New Jersey, New York, Pennsylvania, Rhode Island, Virginia, and the District of Columbia.';
        director = 'Shuana K. Tucker-Sims, Ph.D., Fairfield County (CT) ';
        website = 'https://easternarealinks.org';
        email = 'ealinksts@gmail.com';
      break;
      case 'southern':
        title = "Southern Area";
        imgName = 'southern-area.png';
        description = 'The Southern Area of The Links, Incorporated is comprised of seven states and the Commonwealth of the Bahamas. Southern Area Links hail from the Deep South states of Mississippi and Alabama; the French tradition and Creole culture of Louisiana; the coastal wonders of North and South Carolina; the southern charm of Georgia; the emerald coasts and sugar beaches of sunny Florida, and the sun-drenched tropical beauty of the Bahamas';
        director = 'Sylvia Perry, Bold City (FL) ';
        website = 'https://salinksinc.org';
        email = 'SADirector20@aol.com';
      break;
      case 'central':
        title = "Central Area";
        imgName = 'central-area.png';
        description = 'The Links, Incorporated, founded in 1946, is a women’s volunteer service organization committed to enriching, sustaining and ensuring the cultural and economic survival of African-Americans and other persons of African-American ancestry. A premier international service organization with more than 14,000 members in 281 chapters located in 41 states, the District of Columbia, and the Commonwealth of the Bahamas, continues its legacy of friends providing service that changes lives, established by the original circle of nine friends in Philadelphia, Pennsylvania.';
        director = 'Glenda Masingale Mason, Central Illinois (IL)';
        website = 'https://www.centralarealinks.org ';
        email = 'glendamanson1@icloud.com';
      break;
      case 'western':
        title = "Western Area";
        imgName = 'western-area.png';
        description = 'Drawing on the synergy generated by women who are committed to friendship and service, the Western Area now has 60 chapters, located in ten states — Alaska, Arizona, California, Colorado, Hawaii, Oregon, Nevada, New Mexico, Texas and Washington. Moving forward into the 21st century, Western Area Links are reminded that the legacy of service and friendship provided by the first three chapters continues—as Links make a difference in transforming the lives of people of African ancestry and of the global community.';
        director = 'Roxann Thomas Chargois, Missouri City (TX) ';
        website = 'https://walinks.org';
        email = 'wadirector17@icloud.com';
      break;
    }
    let navigationExtras: NavigationExtras = {
      state: {
        title: title,
        imgName: imgName,
        description: description,
        director: director,
        website: website,
        email: email

      }
    };

    if (param === 'eastern') {
        this.router.navigate(['detail-area-eastern'], navigationExtras);
    } else {
        this.router.navigate(['detail-area'], navigationExtras);
    }
  }
}
